### ISSUE TITLE
Damage management

### ISSUE THREAD

**Issue by SlimeDog** [MostWantedMinx/PyroWeather#12]
Spigot 1.12.2
PyroWeather 1.3.0 + (latest test version)

config.yml (partial)
```
AcidRain:
  Enabled: true
  Worlds:
    - world_yellowdog
  Effects:
    Chance: 100
    Ampliers: 1
    Duration: 25
    Amount: 5
    PotionEffects:
      - CONFUSION
      - HUNGER
      - SLOW
      - SLOW_DIGGING
      - WEAKNESS
  Damage:
    DamageInterval: 5
    MaximumDamage: 2
  Settings:
    StormTime: 180
    Chance: 0
    TimeBetweenChances: 600
    AllStormsAcid: true
    DamageKnockabout: false
    PerWorldAcidRain: false
```

Expected behavior: Every _DamageInterval:5_ seconds, all _Amount:5_ potion effects will be applied for _Duration:25_ seconds. This will ensure that the potion effects continue uninterrupted until either rain stops or player moves under cover. At that point, the effect will continue until the effects countdown timer expires (20-25 seconds, depending on the value of the effects countdown timer), at which point they will stop.

Observed behavior: Once triggered, the potion effects last until the effects countdown timer arrives at 2 seconds, at which point the effects stop. If the player remains in the rain, the effects are started again, and the behavior repeats.
